### ISSUE TITLE
Database specification

### ISSUE THREAD

**Issue by sebpez17** [IMT-Atlantique-FIP2021/fiowebviewer#3]
The actual database store too less information:
- Jobs name
- Jobs submit date
- List of tags
- Link between jobs and tags

In order to improve performance, we want to store FIO results into the database.

Roadmap:
- [x] ~Migrate the actual database to MariaDB~
- [x] Migrate actual database to MongoDB

**Comment by MokoGuy** [comment]
Based on this documentation for **SQLAlchemy** : https://docs.sqlalchemy.org/en/13/intro.html

For mariaDB ? https://docs.sqlalchemy.org/en/13/dialects/mysql.html

**Comment by MokoGuy** [comment]
Example of data sent to the fronend to display the result list:

```json
[
    {
        "id": "result1",
        "name": "FIO Mock-up test 1",
        "tags": ["job1", "INFRA-TEST", "INPUT", "CEPH-DATABASE"],
        "submitted_at": "10/02/2021 22:00"
    }, 
    {
        "id": "result2",
        "name": "FIO Mock-up test 2",
        "tags": ["job1", "INFRA-CLIENT", "INPUT", "OUTPUT", "CEPH-WEB", "Testing"],
        "submitted_at": "15/01/2021 21:00"
    },
    {
        "id": "result3",
        "name": " FIO Mock-up test 3 - Long text that need to be truncated ",
        "tags": ["job3", "INFRA-OVH", "OUTPUT", "CEPH-STORAGE", "Production"],
        "submitted_at": "30/03/2020 19:30"
    },
    {
        "id": "result4",
        "name": " FIO Mock-up test 4",
        "tags": ["NewJob"],
        "submitted_at": "30/03/2020 19:30"
    }
]
```

**Comment by MokoGuy** [comment]
Even better with MongoDB : 

- https://testdriven.io/blog/fastapi-mongo/
